Suicaでお買い物
enteitsuki/shopping pull request #1
Opened 2021-02-23 06:33 UTC by enteitsuki

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise_org/06_shopping/01.md

### メッセージ
Suicaでお買い物 課題完了しました。
確認よろしくおねがいいたします。

2021-02-23 06:59 UTC, kazu-taka requested changes
@enteitsuki 
フローチャートと同じ処理の流れで実装お願いします✨

2021-02-23 06:59 UTC, kazu-taka commented on index.php
> +}
@enteitsuki 
せっかく$chargesを配列で宣言したのであれば、forよりforeachを使うようにして下さい✨

2021-02-23 06:59 UTC, kazu-taka commented on index.php
> +$money = $charges[$answer - 1];
@enteitsuki 
ここは少し分かりにくいような気がするので、$answerだけ判断すれば良い時は、switchを使った方がシンプルでいいと思います✨

2021-02-23 06:59 UTC, kazu-taka commented on index.php
> +while ($money > 0) {
@enteitsuki 
フローチャートで、`買い物フラグがfalseになったら終了`と書いてあるので、フローチャートを参考に、whileの中を修正お願いします！
ループの前に買い物フラグをtrueにする図を追加しました✨

<img src="https://github.com/elites-team/2months_course/raw/master/doc/06_php/exercise_org/06_shopping/images/suica.png">

2021-02-23 09:13 UTC, enteitsuki commented
修正しました。
確認よろしくお願いいたします。

2021-02-23 11:18 UTC, enteitsuki commented
文字列を入力すると、ターミナルに
`Warning: A non-numeric value encountered in /var/www/php_exercise/shopping/index.php on line 12`
と表示されてしまっていたのでint型に修正しました。

2021-02-23 12:07 UTC, kazu-taka requested changes
@enteitsuki 
1箇所だけ修正お願いします😊

2021-02-23 12:07 UTC, kazu-taka commented on index.php
> +    echo $num . ': ' . number_format($charges[$num - 1]) . "円\n";
@enteitsuki 
foreachの使い方間違っているので、もう一度本で復習お願いします✨
インデックスの0から順番に`$charge`セットされるので、$numも不要になり、`number_format($charge)`だけで正しく動きます👍

2021-02-23 20:28 UTC, enteitsuki commented
修正しました。
確認よろしくお願いいたします！

2021-02-23 23:49 UTC, kazu-taka commented
@enteitsuki 
![LGTM](https://image.lgtmoon.dev/117353)

2021-02-24 00:18 UTC, merged

2021-02-24 00:23 UTC, enteitsuki commented
マージしました。
いつもですが難しいです(泣)
基本的な構文を適切につかえたらかっこいいです！
確認頂きありがとうございます！